python main.py --model_name qwen_1.5 --model_type 0.5b
python main.py --model_name qwen_1.5 --model_type chat_0.5b
python main.py --model_name qwen_1.5 --model_type 1.8b
python main.py --model_name qwen_1.5 --model_type chat_1.8b
python main.py --model_name qwen_1.5 --model_type 4b
python main.py --model_name qwen_1.5 --model_type chat_4b
python main.py --model_name qwen_1.5 --model_type 7b
python main.py --model_name qwen_1.5 --model_type chat_7b
python main.py --model_name qwen_1.5 --model_type 14b
python main.py --model_name qwen_1.5 --model_type chat_14b
python main.py --model_name qwen_1.5 --model_type 32b
python main.py --model_name qwen_1.5 --model_type chat_32b
